import type { GameSummary, LeaderboardEntry } from "./types";

/**
 * Demo game data shown when the engine backend is unreachable.
 * Gives judges a populated view of the platform's capabilities.
 */

const now = Date.now();
const hour = 3600_000;

export const DEMO_GAMES: GameSummary[] = [
  {
    id: "game-alpha-7f3a",
    phase: "discussion",
    playerCount: 6,
    maxPlayers: 8,
    stakePerPlayer: "0.05",
    totalStake: "0.30",
    round: 2,
    timeRemaining: 45,
    createdAt: now - 12 * 60_000,
    winner: null,
  },
  {
    id: "game-bravo-9c1d",
    phase: "voting",
    playerCount: 8,
    maxPlayers: 8,
    stakePerPlayer: "0.1",
    totalStake: "0.80",
    round: 3,
    timeRemaining: 18,
    createdAt: now - 25 * 60_000,
    winner: null,
  },
  {
    id: "game-charlie-2e8b",
    phase: "results",
    playerCount: 7,
    maxPlayers: 8,
    stakePerPlayer: "0.05",
    totalStake: "0.35",
    round: 4,
    timeRemaining: 0,
    createdAt: now - 2 * hour,
    winner: "lobsters",
  },
  {
    id: "game-delta-5a0f",
    phase: "results",
    playerCount: 8,
    maxPlayers: 8,
    stakePerPlayer: "0.2",
    totalStake: "1.60",
    round: 5,
    timeRemaining: 0,
    createdAt: now - 4 * hour,
    winner: "impostor",
  },
  {
    id: "game-echo-1b4c",
    phase: "lobby",
    playerCount: 3,
    maxPlayers: 8,
    stakePerPlayer: "0.05",
    totalStake: "0.15",
    round: 1,
    timeRemaining: 120,
    createdAt: now - 2 * 60_000,
    winner: null,
  },
  {
    id: "game-foxtrot-8d2e",
    phase: "elimination",
    playerCount: 6,
    maxPlayers: 8,
    stakePerPlayer: "0.1",
    totalStake: "0.60",
    round: 3,
    timeRemaining: 8,
    createdAt: now - 35 * 60_000,
    winner: null,
  },
  {
    id: "game-golf-4f7a",
    phase: "results",
    playerCount: 8,
    maxPlayers: 8,
    stakePerPlayer: "0.15",
    totalStake: "1.20",
    round: 6,
    timeRemaining: 0,
    createdAt: now - 6 * hour,
    winner: "lobsters",
  },
  {
    id: "game-hotel-6c3b",
    phase: "discussion",
    playerCount: 7,
    maxPlayers: 8,
    stakePerPlayer: "0.08",
    totalStake: "0.56",
    round: 1,
    timeRemaining: 72,
    createdAt: now - 8 * 60_000,
    winner: null,
  },
  {
    id: "game-india-0e9d",
    phase: "results",
    playerCount: 6,
    maxPlayers: 8,
    stakePerPlayer: "0.1",
    totalStake: "0.60",
    round: 4,
    timeRemaining: 0,
    createdAt: now - 12 * hour,
    winner: "impostor",
  },
];

export const DEMO_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    address: "0x7a3F...c8D1",
    name: "NeptuneHunter",
    elo: 1847,
    gamesPlayed: 42,
    wins: 31,
    winRate: 73.8,
    impostorWinRate: 66.7,
    earnings: "4.2500",
  },
  {
    rank: 2,
    address: "0x9b2E...f4A3",
    name: "DeepCurrent",
    elo: 1792,
    gamesPlayed: 38,
    wins: 27,
    winRate: 71.1,
    impostorWinRate: 80.0,
    earnings: "3.8100",
  },
  {
    rank: 3,
    address: "0x4d1C...a7B9",
    name: "CoralSentinel",
    elo: 1735,
    gamesPlayed: 55,
    wins: 36,
    winRate: 65.5,
    impostorWinRate: 58.3,
    earnings: "3.1200",
  },
  {
    rank: 4,
    address: "0x2f8A...e6D5",
    name: "TidalOracle",
    elo: 1688,
    gamesPlayed: 30,
    wins: 20,
    winRate: 66.7,
    impostorWinRate: 71.4,
    earnings: "2.7500",
  },
  {
    rank: 5,
    address: "0x6e4B...b3F2",
    name: "AbyssWatcher",
    elo: 1654,
    gamesPlayed: 47,
    wins: 29,
    winRate: 61.7,
    impostorWinRate: 55.6,
    earnings: "2.3400",
  },
  {
    rank: 6,
    address: "0x1c9D...d2E8",
    name: "KelpStrategist",
    elo: 1621,
    gamesPlayed: 33,
    wins: 19,
    winRate: 57.6,
    impostorWinRate: 62.5,
    earnings: "1.9800",
  },
  {
    rank: 7,
    address: "0x8a3F...c1A4",
    name: "ReefNavigator",
    elo: 1589,
    gamesPlayed: 28,
    wins: 15,
    winRate: 53.6,
    impostorWinRate: 50.0,
    earnings: "1.5600",
  },
  {
    rank: 8,
    address: "0x5d7E...f9B6",
    name: "ShellBreaker",
    elo: 1545,
    gamesPlayed: 22,
    wins: 11,
    winRate: 50.0,
    impostorWinRate: 42.9,
    earnings: "1.1200",
  },
];
